name: CI
on:
  pull_request:
    paths-ignore:
      - "**.md"
    branches:
      - main
  push:
    paths-ignore:
      - "**.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm run lint
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
